const transactions = [
    {
      transactionId: "TXN001",
      companyId: "C001",
      accountHead: "Sales",
      branchId: "B001",
      partyId: "P001",
      date: "2025-01-20",
      autoNarration: "Sold goods to Party P001",
      narration: "Sale of electronic items",
      amount: 1500.0,
      type: "credit",
    },
    {
      transactionId: "TXN002",
      companyId: "C001",
      accountHead: "Purchases",
      branchId: "B002",
      partyId: "P002",
      date: "2025-01-21",
      autoNarration: "Purchased goods from Party P002",
      narration: "Purchase of raw materials",
      amount: 1200.0,
      type: "debit",
    },
    {
      transactionId: "TXN003",
      companyId: "C001",
      accountHead: "Salary",
      branchId: "B001",
      partyId: "P003",
      date: "2025-01-22",
      autoNarration: "Salary paid to Party P003",
      narration: "Monthly salary payment",
      amount: 5000.0,
      type: "debit",
    },
    {
      "transactionId": "objTransId000001",
      "companyId": "objCompId000001",
      "accountHead": "objaccntHeadId0001",
      "branchId": "objBranchId000001",
      "partyId": "objClientId000002",
      "date": "2025-01-23",
      "autoNarration": "Paid electricity bill",
      "narration": "Payment for January electricity bill",
      "amount": 750,
      "type": "debit",
      "clientId": "",
      "_id": "tempId001",
      "b2bDetails":[{invoiceId:'ObjInvoice00001',amount:500},{invoiceId:'ObjInvoice00002',amount:250}]
    },
    {
      transactionId: "TXN005",
      companyId: "C001",
      accountHead: "Freelance Income",
      branchId: "B003",
      partyId: "P005",
      date: "2025-01-24",
      autoNarration: "Received payment from Party P005",
      narration: "Freelance web development project",
      amount: 30000.0,
      type: "credit",
    },
    {
        transactionId: "TXN001",
        companyId: "C001",
        accountHead: "Sales",
        branchId: "B001",
        partyId: "P001",
        date: "2025-01-20",
        autoNarration: "Sold goods to Party P001",
        narration: "Sale of electronic items",
        amount: 1500.0,
        type: "credit",
      },
      {
        transactionId: "TXN002",
        companyId: "C001",
        accountHead: "Purchases",
        branchId: "B002",
        partyId: "P002",
        date: "2025-01-21",
        autoNarration: "Purchased goods from Party P002",
        narration: "Purchase of raw materials",
        amount: 1200.0,
        type: "debit",
      },
      {
        transactionId: "TXN003",
        companyId: "C001",
        accountHead: "Salary",
        branchId: "B001",
        partyId: "P003",
        date: "2025-01-22",
        autoNarration: "Salary paid to Party P003",
        narration: "Monthly salary payment",
        amount: 5000.0,
        type: "debit",
      },
      {
        transactionId: "TXN004",
        companyId: "C001",
        accountHead: "Utilities",
        branchId: "B001",
        partyId: "P004",
        date: "2025-01-23",
        autoNarration: "Paid electricity bill",
        narration: "Payment for January electricity bill",
        amount: 750.0,
        type: "debit",
      },
      {
        transactionId: "TXN005",
        companyId: "C001",
        accountHead: "Freelance Income",
        branchId: "B003",
        partyId: "P005",
        date: "2025-01-24",
        autoNarration: "Received payment from Party P005",
        narration: "Freelance web development project",
        amount: 3000.0,
        type: "credit",
      },
  ];

  
  export default transactions